config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  authenticate :user, ->(u) { u.admin? } do
    ActiveAdmin.routes(self)
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :surveys, only: %i[index new show] do
    resources :user_answers, only: %i[new create]
  end

  resources :places, only: :index

  resources :users, only: :show

  resources :diagnoses, only: %i[new create edit update destroy]

  resources :medications, only: :destroy

  resources :resources

  resources :daily_questions, only: %i[new create]
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_diagnosis, only: %i[edit update destroy]

  def index
    @diagnoses = Diagnosis.all
    @my_diagnoses = current_user.diagnoses
  end

  def new
    @diagnosis = Diagnosis.new
    @my_diagnoses = current_user.diagnoses
    @diagnosis.medications.build
  end

  def edit
    @medication = Medication.new
    @medications = @diagnosis.medications
  end

  def create
    @diagnosis = Diagnosis.new(diagnosis_params)
    @diagnosis.user_id = current_user.id
    if @diagnosis.save
      redirect_to user_path(@diagnosis.user_id), notice: "Diagnosis was successfully created.", status: :see_other
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @diagnosis.update(diagnosis_params)
      redirect_to user_path(@diagnosis.user_id), notice: "Diagnosis was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @diagnosis.destroy
      redirect_to user_path, status: :see_other, notice: "Diagnosis was successfully destroyed."
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def set_diagnosis
    @diagnosis = Diagnosis.find(params[:id])
  end

  def diagnosis_params
    params.require(:diagnosis).permit(:disease, medications_attributes: %i[id name daily_dosage _destroy])
  end
end

app/views/diagnoses/_form.html.erb
<% if @my_medication.present? %>
  <%= simple_form_for(diagnosis, data: {controller: "nested-input", nested_input_medication_id_value: Medication.last.id}) do |f| %>
    <h3>Disease</h3>
    <%= f.input :disease, label: false %>
    <h3>Medications</h3>
    <div class="row" data-nested-input-target="medList">
      <%= render 'medication_input', { diagnosis: @diagnosis, f: f } %>
    </div>
    <div class="card text-end my-2 border-0 rounded-5 align-items-end">
      <a href="#" class="btn btn-primary border-0 rounded-3 btn-sm" data-action="click->nested-input#add">Add medication <i class="fa-solid fa-square-plus"></i></a>
    </div>
    <div class="card text-end my-2 border-0 rounded-5 align-items-end">
      <%= f.submit :Submit, class: 'btn btn-primary border-0 rounded-3 btn-sm', data: { turbo: true } %>
    </div>
  <% end %>
<% else %>
  <%= simple_form_for(diagnosis, data: {controller: "nested-input"}) do |f| %>
    <h3>Disease</h3>
    <%= f.input :disease, label: false %>
    <h3>Medications</h3>
    <div class="row" data-nested-input-target="medList">
      <%= render 'medication_input', { diagnosis: @diagnosis, f: f } %>
    </div>
    <div class="card text-end my-2 border-0 rounded-5 align-items-end">
      <a href="#" class="btn btn-primary border-0 rounded-3 btn-sm" data-action="click->nested-input#add">Add medication <i class="fa-solid fa-square-plus"></i></a>
    </div>
    <div class="card text-end my-2 border-0 rounded-5 align-items-end">
      <%= f.submit :Submit, class: 'btn btn-primary border-0 rounded-3 btn-sm', data: { turbo: true } %>
    </div>
  <% end %>
<% end %>

app/views/diagnoses/_medication_input.html.erb
<%= f.simple_fields_for :medications do |med| %>
  <div class="col-11" data-nested-input-target="medFields">
    <div class="row">
      <div class="col-5 border-0 rounded-5">
        <%= med.input :name, label: false, placeholder: 'Medication' %>
      </div>
      <div class="col-6 border-0 rounded-5">
        <%= med.input :daily_dosage, label: false, placeholder: 'Daily dosage' %>
      </div>
    </div>
  </div>
  <div class="col-1">
    <% if diagnosis.persisted? %>
      <% diagnosis.medications.each do |medication| %>
        <div class="row mb-3">
          <%= link_to medication_path(medication), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-regular fa-circle-xmark"></i>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/diagnoses/edit.html.erb
<div class="container mt-4">
  <div class="cards col-12 col-lg-6 border-0 rounded-5 p-2">
    <div class="card mb-5 border-0 rounded-5">
      <h1 class="text-center mt-1 mb-0 text-uppercase align-bottom fw-bolder">EDIT DIAGNOSIS</h1>
    </div>
    <div class="card mb-5 p-4 border-2 rounded-5">
      <%= render 'form', { diagnosis: @diagnosis } %>
    </div>
    <div>
      <p><%= link_to "My profile", user_path(current_user), class: "btn btn-primary rounded-3" %></p>
    </div>
  </div>
</div>

app/views/diagnoses/new.html.erb
<div class="container mt-4">
  <div class="cards col-12 col-lg-6 border-0 rounded-5 p-2">
    <div class="card mb-5 border-0 rounded-5">
      <h1 class="text-center mt-1 mb-0 text-uppercase align-bottom fw-bolder">ADD NEW DIAGNOSIS</h1>
    </div>
    <div class="card mb-5 p-4 border-2 rounded-5">
      <%= render 'form', { diagnosis: @diagnosis } %>
    </div>
    <div>
      <p><%= link_to "My profile", user_path(current_user), class: "btn btn-primary rounded-3" %></p>
    </div>
  </div>
</div>