config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  authenticate :user, ->(u) { u.admin? } do
    ActiveAdmin.routes(self)
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :surveys, only: %i[index new show] do
    resources :user_answers, only: %i[new create]
  end

  resources :places, only: :index

  resources :users, only: :show

  resources :diagnoses, only: %i[new create edit update destroy]

  resources :medications, only: :destroy

  resources :resources

  resources :daily_questions, only: %i[new create]
end

app/views/resources/index.html.erb
<div class= "container" >

  <div class="banner" min-height= 100%; border-radius-xl; style="background-image: linear-gradient(rgba(0,0,0,0.65),rgba(0,0,0,0.65)), url(https://cdn11.bigcommerce.com/s-2t5fkq8mli/images/stencil/960w/uploaded_images/family-double-piggyback-small.jpg?t=1659564456);">
    <div class="container">
     <h1><em>Your</em> health in <em>your</em> hands</h1>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-8 my-3 mb-4">
      <%= form_with url: resources_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class = "cards-resources">
    <% @resources.each do |resource| %>
      <%= link_to resource_path(resource), class: 'text-decoration-none' do %>
        <%#= adding cloudinary function to show castle images %>
        <%#=if user uploads the picture then it's going to show, else it's showing the DB picture %>
        <div class="card-category mb-3" >
          <h1><%= resource.name %></h1>
        </div>
      <% end %>
    <% end %>
  </div>



</div>

app/views/resources/show.html.erb
<div class= "container" >
 <% content_for :meta_title, "#{@resource.name} is on #{DEFAULT_META["meta_product_name"]}" %>
 <% content_for :meta_description, @resource.details %>

  <div class="banner" min-height= 100%; border-radius-xxl; style="background-image: linear-gradient(rgba(0,0,0,0.55),rgba(0,0,0,0.55)), url(https://res.cloudinary.com/dxmscduce/image/upload/v1725649741/favela_xa3oro.jpg);">
    <div class="container">
     <h1><%= @resource.name %></h1>
    </div>
  </div>

  <p class="m-3 p-3"><%= @match_data[1] %></p>
  <p class="m-3 p-3"><%= @match_data[2] %></p>
  <p class="m-3 p-3"><%= @match_data[3] %></p>

  <div class="button mb-4">
    <%= link_to "Back to all", :back, class: "btn btn-primary" %>
  </div>

</div>