config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  authenticate :user, ->(u) { u.admin? } do
    ActiveAdmin.routes(self)
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :surveys, only: %i[index new show] do
    resources :user_answers, only: %i[new create]
  end

  resources :places, only: :index

  resources :users, only: :show

  resources :diagnoses, only: %i[new create edit update destroy]

  resources :medications, only: :destroy

  resources :resources

  resources :daily_questions, only: %i[new create]
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, through: :questions
  # validates :title, :interval_days, presence: true

  # validates :interval_days, numericality: { greater_than: 0 }
  # ---------------------------------
  # ChatGPT custom validation code 👇
  # ---------------------------------

  validate :integer_array_items_are_positive_integers

  # Serialize the array so that it's stored as a text column in the database
  # serialize :integer_array, Array

  private

  def integer_array_items_are_positive_integers
    if interval_days.present?
      interval_days.each do |item|
        unless item.is_a?(Integer) && item.positive?
          errors.add(:interval_days, "contains an invalid item: #{item.inspect}")
        end
      end
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[show destroy]

  def index
    @survey = Survey.all
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
  end

  def destroy
    @survey.destroy
  end

  def show
    @user_answer = UserAnswer.new
  end

  private

  def survey_params
    params.require(:survey).permit(:title, :interval_days)
  end

  def set_survey
    @survey = Survey.find(params[:id])
  end
end

app/views/surveys/_form.html.erb
<div class="container">
  <div class="row col-6 mt-3 mb-5">
    <%= simple_form_for(@survey) do |f| %>
      <div data-toggle-target="errors">
        <%= f.error_notification %>
      </div>
      <%= f.input :title %>
      <%= f.input :interval_days %>
      <%= f.submit :Create, class: 'btn btn-primary my-custom-class' %>
    <% end %>
  </div>
</div>

app/views/surveys/index.html.erb
<div class="container">
    <ul class="m-0 p-0">
        <% @survey.each do |survey| %>
          <div>
            <li>
              <%= link_to survey.title, survey_path(survey), id:"survey-btn", class: "btn btn-primary d-flex align-items-center text-center" %>
            </li>
          </div>
        <% end %>
    </ul>
</div>

app/views/surveys/new.html.erb
<div class="container">
  <h1>Add a new Survey</h1>

  <%= render 'form', status: :unprocessable_entity %>

  <div>
    <p><%= link_to "back to list", root_path,
           class: "btn btn-primary" %></p>
  </div>
</div>

app/views/surveys/show.html.erb
<div class="container">
  <% content_for :meta_title, "#{@survey.title} is on #{DEFAULT_META["meta_product_name"]}" %>

  <h1 class="text-center my-4"><%= @survey.title %></h1>
</div>
<div class="container d-flex flex-column">
  <span class="btn btn-primary btn-lg w-100 mt-5">
    <%= link_to "Start survey",
        new_survey_user_answer_path(@survey, question_index: 0),
        class: "text-light text-decoration-none strong" %>
  </span>
</div>